name: å‘å¸ƒé¢„è§ˆç‰ˆ

on:
  push:
    branches:
      - main
      - '!release-please*'
  pull_request_target:
    types: 
    - opened
    - reopened
    - synchronize
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  beta-version:
    if: "!startsWith(github.head_ref, 'release-please')"
    runs-on: ubuntu-latest
    outputs:
      beta_version: ${{ steps.set-version.outputs.BETA_VERSION }}
      short_commit_hash: ${{ steps.get-sha.outputs.SHORT_COMMIT_HASH }}
      build_timestamp: ${{ steps.get-build-timestamp.outputs.BUILD_TIMESTAMP }}
      package_name: ${{ steps.set-version.outputs.PACKAGE_NAME }}
      package_short_name: ${{ steps.set-version.outputs.PACKAGE_SHORT_NAME }}

    steps:
      - name: æ£€å‡ºä»£ç 
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - name: è®¾ç½® pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: ç”Ÿæˆ Beta ç‰ˆæœ¬å·
        id: set-version
        run: |
          branch=${{ github.event.pull_request.head.ref || github.ref_name }}
          git fetch origin $branch --depth=100
          git checkout $branch
          RELEASE_BRANCH="release-please--branches--main--components--logger"
          if git ls-remote --heads origin $RELEASE_BRANCH | grep -q $RELEASE_BRANCH; then
            git fetch origin $RELEASE_BRANCH --depth=1
            git checkout FETCH_HEAD -- package.json
            VERSION=$(pnpm pkg get version | tr -d '"')
            git checkout $branch -- package.json
          else
            VERSION=$(pnpm pkg get version | tr -d '"')
          fi       
          BETA_VERSION="$VERSION-beta.$(date +%s)"

          PACKAGE_NAME=$(pnpm pkg get name | tr -d '"')
          PACKAGE_SHORT_NAME=$(pnpm pkg get name | tr -d '"' | awk -F'/' '{print $2}')
          echo "PACKAGE_SHORT_NAME=$PACKAGE_SHORT_NAME" >> $GITHUB_ENV
          echo "PACKAGE_SHORT_NAME=$PACKAGE_SHORT_NAME" >> $GITHUB_OUTPUT
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_OUTPUT
          echo "BETA_VERSION=$BETA_VERSION" >> $GITHUB_ENV
          echo "BETA_VERSION=$BETA_VERSION" >> $GITHUB_OUTPUT
          echo "ç”Ÿæˆçš„ Beta ç‰ˆæœ¬å·: $BETA_VERSION"
          
      - name: è·å–åˆ†æ”¯çš„æœ€æ–°æäº¤å“ˆå¸Œ
        id: get-sha
        run: |
          branch=${{ github.event.pull_request_target.head.ref || github.ref_name }}
          git fetch --depth=1 origin $branch
          SHORT_COMMIT_HASH=$(git rev-parse --short FETCH_HEAD)
          echo "SHORT_COMMIT_HASH=$SHORT_COMMIT_HASH" >> $GITHUB_ENV
          echo "SHORT_COMMIT_HASH=$SHORT_COMMIT_HASH" >> $GITHUB_OUTPUT
          echo "åˆ†æ”¯ $branch çš„æœ€æ–°çŸ­å“ˆå¸Œä¸º: $SHORT_COMMIT_HASH"

      - name: è·å–æ„å»ºæ—¶é—´
        id: get-build-timestamp
        run: |
          branch=${{ github.event.pull_request.head.ref || github.ref_name }}
          git fetch origin $branch --depth=1
          BUILD_TIMESTAMP_UTC=$(git show -s --format=%cd --date=iso-strict origin/$branch)
          echo "BUILD_TIMESTAMP_UTC=$BUILD_TIMESTAMP_UTC"
          BUILD_TIMESTAMP=$(TZ=Asia/Shanghai date -d "$BUILD_TIMESTAMP_UTC" +"%Y-%m-%d %H:%M:%S")

          echo "BUILD_TIMESTAMP=$BUILD_TIMESTAMP" >> $GITHUB_ENV
          echo "BUILD_TIMESTAMP=$BUILD_TIMESTAMP" >> $GITHUB_OUTPUT
          echo "æ„å»ºæ—¶é—´: $BUILD_TIMESTAMP"

  build:
    needs: beta-version
    uses: ./.github/workflows/build.yaml

  publish-to-pkg-pr-new:
    needs: [beta-version, build]
    runs-on: ubuntu-latest
    steps:
      - name: è·å–token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      
      - name: å¯¼å…¥æ„å»ºäº§ç‰©
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: puppeteer-core
          path: ./

      - name: è®¾ç½® pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        
      - name: å‘å¸ƒé¢„è§ˆç‰ˆ
        run: |
          pnpm dlx pkg-pr-new publish --json output.json --comment=off > pkg-output.txt 2>&1
          
          echo "## æˆåŠŸæ¨é€çš„PackageåŒ… :" >> $GITHUB_STEP_SUMMARY
          echo "åŒ…å: \`${{ needs.beta-version.outputs.package_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "ç‰ˆæœ¬å·: \`${{ needs.beta-version.outputs.beta_version }}\`" >> $GITHUB_STEP_SUMMARY
          echo "æäº¤: \`${{ needs.beta-version.outputs.short_commit_hash }}\`" >> $GITHUB_STEP_SUMMARY
          echo "å‘å¸ƒæ—¶é—´: \`${{ needs.beta-version.outputs.build_timestamp }}\`" >> $GITHUB_STEP_SUMMARY
          echo "å‘å¸ƒè€…: \`${{ github.actor }}\`" >> $GITHUB_STEP_SUMMARY
          echo "ä½¿ç”¨ pnpm:" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "pnpm install https://pkg.pr.new/${{ github.repository }}/${{ needs.beta-version.outputs.package_name }}@${{ needs.beta-version.outputs.short_commit_hash }}" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

          echo "## å®Œæ•´è¾“å‡ºä¿¡æ¯" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat pkg-output.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY


      - name: å‘å¸ƒ PR è¯„è®º
        if: github.event_name == 'pull_request_target'
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          pr-number: ${{ github.event.pull_request_target.number }}
          message: |
            ğŸ‰ ğŸ‰ ğŸ‰ **æ„å»ºå®Œæˆï¼**
            è¯¥ç‰ˆæœ¬æ˜¯åŸºäº `${{ github.event.pull_request.head.ref || github.ref_name }}` åˆ†æ”¯çš„å¿«ç…§ [**`${{ needs.beta-version.outputs.short_commit_hash }}`**](https://github.com/${{ github.repository }}/commit/${{ needs.beta-version.outputs.short_commit_hash }}) æ‰€æ„å»ºçš„ã€‚

            ä½ å¯ä»¥é€šè¿‡ä»¥ä¸‹å‘½ä»¤å®‰è£…è¯¥ç‰ˆæœ¬ï¼š
            ```
            pnpm install https://pkg.pr.new/${{ github.repository }}/${{ needs.beta-version.outputs.package_name }}@${{ needs.beta-version.outputs.short_commit_hash }}
            ```

      - name: ä¸Šä¼ NPMåŒ…ä¿¡æ¯
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: npm-package-info
          path: |
            pkg-output.txt
            output.json
